FletEX/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FletEX.Models;

namespace FletEX.Controllers
{
    public class ChartController : Controller
    {
        private FletXEntities db = new FletXEntities();
        // GET: Chart
        public ActionResult Index()
        {
            return View(db.Projects.ToList());
        }

        // GET: Chart/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Chart/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Chart/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Chart/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Chart/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Chart/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Chart/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public PartialViewResult Chart()
        {
            return PartialView();
        }

        public ActionResult YearProjectChart(int pid)
        {
            var myChart = new System.Web.Helpers.Chart(width: 600, height: 400);

            myChart.SetYAxis("", 2000, 2100);
            myChart.AddTitle("Chart Title");

            List<string> list = new List<string>();
            List<string> list2 = new List<string>();
            foreach (var item in db.Projects)
            {
                list.Add(item.Name);
                list2.Add(item.DateStart.Year.ToString());

            }
            myChart.AddSeries(name: "Projetcs", xValue: list.ToArray(), yValues: list2.ToArray());

            myChart.GetBytes("jpeg");

            var mChart = myChart.GetBytes("jpeg");

            return File(mChart, "image/jpeg");
        }

    }
}

FletEX/Views/Chart/Chart.cshtml
@model IEnumerable<FletEX.Models.Projects>

<table class="table">
    @{
        var myChart = new Chart(width: 600, height: 400);

        myChart.SetYAxis("", 2000, 2100);
        myChart.AddTitle("Chart Title");

        List<string> list = new List<string>();
        List<string> list2 = new List<string>();
        foreach (var item in Model)
        {
            list.Add(item.Name);
            list2.Add(item.DateStart.Year.ToString());

        }
        myChart.AddSeries(name: "Projetcs", xValue: list.ToArray(), yValues: list2.ToArray());
        myChart.Save("~/Content/chart" + "Grafico", "jpeg");

    }
</table>

FletEX/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Gráfico - Ano Projeto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript" src="~/Scripts/jquery-1.7.1.min.js"></script>
<script type="text/javascript"> function atualizarDefinicao() { $.ajax( { type: 'GET', url: '/Home/Chart', dataType: 'html', cache: false, async: true, success: function (data) { $('#chart').html(data); } }); } $(document).ready(function () { setInterval(atualizarDefinicao, 30000); }); </script>

<h2>Index</h2>

<div id="chart">

    <img src="@Url.Action("YearProjectChart", "Chart", new { pid = 1 })" />
</div>

<div>
    @Html.ActionLink("Back to List", "../Projects/Index")
</div>